/**
 * Building a `gb` ROM — by patching, not by assembling.
 *
 * The runtime is a *fixed* engine (doc 14 §2), so a game changes the tables and
 * nothing else. That makes a build a byte patch into a pre-assembled image
 * rather than a toolchain invocation, and three things fall out of it that are
 * worth more than the assembler was:
 *
 *   - **The browser can build a ROM.** Doc 13 §D5 wants the web app to play a
 *     real ROM, and it can, because patching needs no RGBDS — it needs a
 *     `Uint8Array` and a checksum.
 *   - **`demake build` works on a bare machine.** No toolchain to provision,
 *     nothing to version-pin at the point of use.
 *   - **The CLI and the web produce identical bytes**, which is the doc-07
 *     parity contract restated for games instead of images.
 *
 * The assembled image is checked in and regenerated by `pnpm gen:runtime`, with
 * a staleness test in the same shape as the man pages (doc 05): the tool that
 * needs RGBDS runs at authoring time, not at build time.
 *
 * The Nintendo logo area is left as zeros, exactly as the NDS builder leaves
 * its logo area (doc 06): we ship no copyrighted data. Emulators that direct
 * boot — including `@demake/dmg` and the libretro cores — do not look at it;
 * original hardware does, so `demake build` runs `rgbfix` to stamp it when
 * RGBDS happens to be installed, and says so when it is not.
 */

import type { Program } from "../program.js";

import { DATA_BASE, DATA_SIZE } from "./format.js";
import { RUNTIME_GB } from "./runtime-gb.generated.js";
import { emitTables, type TableStats, TableError } from "./tables.js";

/** Bytes in a mapper-less Game Boy cartridge. */
export const ROM_SIZE = 0x8000;

/** Header field offsets, for callers that want to read a built ROM back. */
export const HEADER_OFFSETS = {
  logo: 0x0104,
  title: 0x0134,
  cgb: 0x0143,
  cartridgeType: 0x0147,
  romSize: 0x0148,
  ramSize: 0x0149,
  headerChecksum: 0x014d,
  globalChecksum: 0x014e,
} as const;

/** What to stamp in the cartridge header. */
export interface RomOptions {
  /** Cartridge title: up to 15 characters, upper-cased ASCII. */
  title?: string;
}

/** A built ROM and what went into it. */
export interface BuiltRom {
  bytes: Uint8Array;
  stats: TableStats;
}

/**
 * Language features this runtime does not implement yet.
 *
 * Refusing is the whole point. A runtime that silently ignored a level would
 * produce a ROM that plays a *different game* from the preview and from the
 * golden trace, and the trace oracle would report a divergence whose cause is
 * three layers away. Naming it here makes the gap a build error with a fix.
 */
export function unsupportedFeatures(program: Program): string[] {
  const missing: string[] = [];
  if (program.scenes.some((scene) => scene.level)) {
    missing.push("levels and tile collision (`level` / `stream`)");
  }
  if (program.scenes.some((scene) => scene.cameraTarget !== undefined)) {
    missing.push("a scrolling camera (`camera follows`)");
  }
  return missing;
}

/** Build a bootable `.gb` for a compiled program. */
export function buildGbRom(program: Program, options: RomOptions = {}): BuiltRom {
  const missing = unsupportedFeatures(program);
  if (missing.length > 0) {
    throw new TableError(
      "E_RUNTIME_UNSUPPORTED",
      `the gb runtime does not implement ${missing.join(" or ")} yet`,
      "the preview runs it; the ROM would play a different game, so the build stops here",
    );
  }

  const { bytes: tables, stats } = emitTables(program, DATA_BASE);
  const rom = new Uint8Array(ROM_SIZE);
  rom.set(decodeBase64(RUNTIME_GB), 0);
  if (tables.length > DATA_SIZE) {
    throw new TableError(
      "E_GAME_TOO_LARGE",
      `the program tables need ${tables.length} bytes and the ROM's data window holds ${DATA_SIZE}`,
    );
  }
  rom.set(tables, DATA_BASE);
  writeHeader(rom, options.title ?? "DEMOTIC");
  return { bytes: rom, stats };
}

/**
 * Stamp the cartridge header and both checksums.
 *
 * Checksums are computed and never authored — the same rule doc 15 §header
 * states for every family, and the reason a Demakefile cannot produce an
 * invalid header by omission.
 */
function writeHeader(rom: Uint8Array, title: string): void {
  const clean = title
    .toUpperCase()
    .replace(/[^\x20-\x5f]/g, " ")
    .slice(0, 15);
  for (let index = 0; index < 16; index += 1) {
    rom[HEADER_OFFSETS.title + index] = index < clean.length ? clean.charCodeAt(index) : 0;
  }
  rom[HEADER_OFFSETS.cgb] = 0x00;
  rom[0x0144] = 0x00;
  rom[0x0145] = 0x00;
  rom[0x0146] = 0x00; // no Super Game Boy functions
  rom[HEADER_OFFSETS.cartridgeType] = 0x00; // ROM only: 32 KiB, no mapper
  rom[HEADER_OFFSETS.romSize] = 0x00;
  rom[HEADER_OFFSETS.ramSize] = 0x00;
  rom[0x014a] = 0x01; // non-Japanese
  rom[0x014b] = 0x33; // "see the new licensee code"
  rom[0x014c] = 0x00; // version

  let header = 0;
  for (let at = 0x0134; at <= 0x014c; at += 1) header = (header - (rom[at] as number) - 1) & 0xff;
  rom[HEADER_OFFSETS.headerChecksum] = header;

  rom[HEADER_OFFSETS.globalChecksum] = 0;
  rom[HEADER_OFFSETS.globalChecksum + 1] = 0;
  let global = 0;
  for (const byte of rom) global = (global + byte) & 0xffff;
  rom[HEADER_OFFSETS.globalChecksum] = (global >> 8) & 0xff;
  rom[HEADER_OFFSETS.globalChecksum + 1] = global & 0xff;
}

const BASE64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/**
 * Decode the embedded runtime image.
 *
 * Written out because `atob` is a DOM API and `Buffer` is a Node one, and this
 * package may use neither (doc 02 §platform purity). Fourteen lines is a
 * cheaper price than a conditional import that would make the browser and the
 * CLI take different paths to the same bytes.
 */
export function decodeBase64(text: string): Uint8Array {
  const lookup = new Int8Array(128).fill(-1);
  for (let index = 0; index < BASE64.length; index += 1) {
    lookup[BASE64.charCodeAt(index)] = index;
  }
  let bits = 0;
  let width = 0;
  const out: number[] = [];
  for (let index = 0; index < text.length; index += 1) {
    const value = lookup[text.charCodeAt(index)] as number;
    if (value < 0) continue;
    bits = (bits << 6) | value;
    width += 6;
    if (width >= 8) {
      width -= 8;
      out.push((bits >> width) & 0xff);
    }
  }
  return Uint8Array.from(out);
}

/** Encode bytes the way `pnpm gen:runtime` writes them. */
export function encodeBase64(bytes: Uint8Array): string {
  let text = "";
  for (let at = 0; at < bytes.length; at += 3) {
    const a = bytes[at] as number;
    const b = bytes[at + 1];
    const c = bytes[at + 2];
    text += BASE64[a >> 2];
    text += BASE64[((a & 3) << 4) | ((b ?? 0) >> 4)];
    text += b === undefined ? "=" : BASE64[((b & 15) << 2) | ((c ?? 0) >> 6)];
    text += c === undefined ? "=" : BASE64[c & 63];
  }
  return text;
}
