/**
 * `gb` family ROM building (doc 06 §ROM building, doc 10).
 *
 * `core` emits platform-pure data; assembling a bootable ROM needs a toolchain,
 * which lives here at the CLI edge. We take the generated RGBDS `asm` (symbol
 * prefix `demake`), drop it next to the on-disk harness in a temp dir, and run
 * the local RGBDS (`rgbasm`→`rgblink`→`rgbfix`) — the same tools CI uses. If the
 * toolchain is absent, we fail with a clear, actionable `E_TOOLCHAIN_MISSING`
 * (install it with `tools/toolchains/install-rgbds.sh`).
 *
 * **Three consoles, one harness.** The Mega Duck is a Game Boy clone whose I/O
 * pins were rewired, so it is a *variant* on the terms AGENTS.md §How to add a
 * console sets out — it costs a machine description and not one instruction.
 * {@link machineInclude} is that description, written beside the harness and
 * built from `core/src/asm/megaduck.ts` rather than restated, and the two other
 * places this console differs are both here rather than in the display program:
 * there is no `rgbfix` step, because a Mega Duck cartridge has no header, no
 * logo and no checksum for one to write; and the padding to 32 KiB is therefore
 * ours.
 */

import { join } from "node:path";

import { lcdcToDuck, megaduckRegister, MEGADUCK_ROM_SIZE, type ConsoleSpec } from "@demake/core";

import type { CliEnv } from "../env.js";
import { EXIT } from "../exit-codes.js";
import { CliError } from "../io.js";

/** RGBDS versions we build and test against (allow-listed, doc 06). */
const ALLOWED_VERSIONS = [/^0\.8\./, /^0\.9\./];
const RGBDS_TOOLS = ["rgbasm", "rgblink", "rgbfix"] as const;

const INSTALL_HINT =
  "install RGBDS (e.g. run tools/toolchains/install-rgbds.sh, or `pnpm toolchains`), " +
  "or emit bin/asm/c and assemble it yourself.";

function toolchainError(message: string): CliError {
  return new CliError(EXIT.UNAVAILABLE, "E_TOOLCHAIN_MISSING", message, INSTALL_HINT);
}

/** Assert every RGBDS tool is present and version-allowed; returns its version. */
function requireToolchain(env: CliEnv): string {
  for (const tool of RGBDS_TOOLS) {
    if (!env.which(tool)) throw toolchainError(`RGBDS tool '${tool}' is not on PATH`);
  }
  const probe = env.run("rgbasm", ["--version"], ".");
  const version = /v?(\d+\.\d+\.\d+)/.exec(probe.stdout + probe.stderr)?.[1];
  if (!version) throw toolchainError("could not determine the RGBDS version");
  if (!ALLOWED_VERSIONS.some((re) => re.test(version))) {
    throw toolchainError(
      `unsupported RGBDS v${version} (need ${ALLOWED_VERSIONS.map(String).join(" or ")})`,
    );
  }
  return version;
}

/** The Game Boy `LCDC` the harness shows a picture with: LCD + BG on, tiles at $8000. */
const LCDC_SHOW = 0b1001_0001;

/**
 * The machine half of the harness: which addresses its registers are at.
 *
 * A Mega Duck's are the Game Boy's put through `core`'s own table — the same one
 * `@demake/dmg` routes a write with and the audio driver emits a store from — so
 * this display program is the Game Boy's with three equates changed. `DUCK` is
 * the switch for the two structural facts a number cannot carry: no cartridge
 * header, and therefore no `rgbfix`.
 */
function machineInclude(spec: ConsoleSpec): string {
  const duck = spec.id === "megaduck";
  const at = (register: number): string =>
    `$FF${(duck ? megaduckRegister(register) : register).toString(16).toUpperCase().padStart(2, "0")}`;
  const lines = [
    "; Generated by demake from core/src/asm/megaduck.ts — do not edit.",
    `; Machine: ${spec.id}`,
    `DEF rLCDC EQU ${at(0x40)}`,
    `DEF rBGP  EQU ${at(0x47)}`,
    `DEF rLY   EQU ${at(0x44)}`,
    `DEF LCDC_SHOW EQU $${(duck ? lcdcToDuck(LCDC_SHOW) : LCDC_SHOW).toString(16).toUpperCase()}`,
  ];
  if (duck) lines.push("DEF DUCK EQU 1");
  else {
    // A Mega Duck has no colour path at all, so these are the Game Boy Color's
    // and are emitted only where one exists — an address on this console with
    // nothing behind it is `MEGADUCK_UNMAPPED`, not itself.
    lines.push(
      "DEF rVBK  EQU $FF4F ; CGB VRAM bank select",
      "DEF rBCPS EQU $FF68 ; CGB BG palette index (bit 7 = auto-increment)",
      "DEF rBCPD EQU $FF69 ; CGB BG palette data",
    );
  }
  return lines.join("\n") + "\n";
}

/**
 * Build a bootable `.gb`/`.gbc`/`.duck` from the generated `gb` data (RGBDS
 * `asm` with the `demake` symbol prefix). Throws a structured {@link CliError}
 * on missing toolchain or a build failure.
 */
export function buildGbRom(env: CliEnv, spec: ConsoleSpec, dataAsm: Uint8Array): Uint8Array {
  requireToolchain(env);

  const harnessRoot = env.harnessDir();
  if (!harnessRoot) {
    throw new CliError(
      EXIT.INTERNAL,
      "E_HARNESS_MISSING",
      "could not locate rom-harness/ in the repo",
    );
  }
  const harnessPath = join(harnessRoot, "gb", "main.asm");
  let harness: Uint8Array;
  try {
    harness = env.readFile(harnessPath);
  } catch {
    throw new CliError(EXIT.INTERNAL, "E_HARNESS_MISSING", `cannot read harness '${harnessPath}'`);
  }

  const isColor = spec.color.model === "rgb";
  const isDuck = spec.id === "megaduck";
  const dir = env.makeTempDir("demake-rom-");
  try {
    env.writeFileAtomic(join(dir, "machine.asm"), asciiFile(machineInclude(spec)), true);
    env.writeFileAtomic(join(dir, "demake.asm"), dataAsm, true);
    env.writeFileAtomic(join(dir, "main.asm"), harness, true);

    runStep(env, dir, "rgbasm", ["-o", "main.o", "main.asm"]);
    runStep(env, dir, "rgblink", ["-o", "out.gb", "main.o"]);
    if (isDuck) {
      // Nothing to fix: this console has no header, no logo and no checksum, so
      // the only thing left is the pad to the one board it takes.
      const linked = env.readFile(join(dir, "out.gb"));
      if (linked.length > MEGADUCK_ROM_SIZE) {
        throw new CliError(
          EXIT.FAILURE,
          "E_ROM_TOO_LARGE",
          `the Mega Duck program is ${linked.length} bytes; the cartridge is ${MEGADUCK_ROM_SIZE}`,
          "prep to a smaller size, or emit bin/asm and write your own loader.",
        );
      }
      const rom = new Uint8Array(MEGADUCK_ROM_SIZE).fill(0xff);
      rom.set(linked, 0);
      return rom;
    }
    // rgbfix writes the Nintendo logo, header, and checksums; -C marks a CGB ROM.
    runStep(
      env,
      dir,
      "rgbfix",
      isColor ? ["-v", "-C", "-p", "0xFF", "out.gb"] : ["-v", "-p", "0xFF", "out.gb"],
    );

    return env.readFile(join(dir, "out.gb"));
  } finally {
    env.removeDir(dir);
  }
}

/** ASCII bytes for a generated source file. */
function asciiFile(text: string): Uint8Array {
  const out = new Uint8Array(text.length);
  for (let i = 0; i < text.length; i += 1) out[i] = text.charCodeAt(i) & 0x7f;
  return out;
}

function runStep(env: CliEnv, cwd: string, tool: string, args: readonly string[]): void {
  const r = env.run(tool, args, cwd);
  if (r.code !== 0) {
    const detail = (r.stderr || r.stdout).trim().split("\n").slice(0, 4).join("; ");
    throw new CliError(
      EXIT.FAILURE,
      "E_ROM_BUILD_FAILED",
      `${tool} failed (exit ${r.code})${detail ? `: ${detail}` : ""}`,
      "this is likely a harness/toolchain mismatch; please file a bug with the input.",
    );
  }
}
