/**
 * Browser ⇄ Node determinism (doc 07 §Principles: "parity is a contract",
 * doc 10 §Determinism tests).
 *
 * The claim under test is exact: converting the same image with the same
 * options must produce **byte-identical** output in the browser and on the
 * command line — in every engine. So each case runs `prep` twice: once here in
 * Node through `@demake/core`, once in the page through its Web Worker, and the
 * two PNGs are compared byte-for-byte (via SHA-256 plus a length check).
 *
 * The page is driven through its real export path — the same download button a
 * user clicks — so nothing test-only stands in for the product.
 *
 * The subject is the bundled demo image, which is generated by shared code with
 * no transcendentals or randomness, so "the same input" is itself provable
 * rather than assumed.
 *
 * The same contract is then checked for a *game*, on both consoles the page can
 * build: it compiles a `.dmt` to SM83 or to 6502 and demakes its SVG art with no
 * toolchain and no host rasteriser, so the cartridge it hands you must be
 * byte-identical to the one `demake build` writes. That is the harder half — a
 * cartridge is tens of kilobytes of code, tile bytes and checksums, and every one
 * of those has to agree.
 *
 * And for *audio*, where doc 07 states it outright: the audio exported in the
 * page must be byte-identical to the audio exported in Node. That is what makes
 * "Web Audio is a playback device, never a synthesizer" a checkable claim rather
 * than an intention — a browser-synthesized approximation would fail here in the
 * first hundred samples.
 */

import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

import {
  arrangeScore,
  buildAudioRom,
  demakeSfx,
  encodeAudioManifest,
  encodeWav,
  parseMidi,
  arrangeManifest,
  render,
  sfxManifest,
} from "@demake/audio";
import { encodeRgbaPng, prep } from "@demake/core";
import { buildGame, compile, getProfile } from "@demake/demotic";
import { expect, test, type Page } from "@playwright/test";

import {
  DEFAULT_ARRANGE,
  DEFAULT_SFX,
  toArrangeOptions,
  toRenderOptions,
  toSfxOptions,
} from "../../src/lib/audio-options.ts";
import { buildDemoImage } from "../../src/lib/demo-image.ts";
import { toPrepOptions, DEFAULT_OPTIONS } from "../../src/lib/options.ts";
import type { PrepOptionsUi } from "../../src/worker/protocol.ts";

const sha256 = (bytes: Uint8Array): string =>
  createHash("sha256").update(Buffer.from(bytes)).digest("hex");

/** The exact bytes the app's "Load demo image" button feeds the engine. */
function demoPng(): Uint8Array {
  const { width, height, data } = buildDemoImage();
  return encodeRgbaPng(width, height, data);
}

/**
 * Cases chosen to exercise different pipeline corners: the mono path, a
 * fixed-master console with 16×16 attribute cells, a 15-bit RGB console with an
 * explicit dither, and a run with a non-default seed and effort.
 */
const CASES: { name: string; options: PrepOptionsUi }[] = [
  { name: "gbc-default", options: { ...DEFAULT_OPTIONS } },
  { name: "dmg-mono", options: { ...DEFAULT_OPTIONS, console: "dmg" } },
  { name: "nes-fixed-master", options: { ...DEFAULT_OPTIONS, console: "nes", effort: "fast" } },
  {
    name: "snes-dithered",
    options: { ...DEFAULT_OPTIONS, console: "snes", dither: "bayer4", seed: "1234" },
  },
];

for (const { name, options } of CASES) {
  test(`browser output is byte-identical to Node — ${name}`, async ({ page }) => {
    // 1. Node: the CLI's engine, called exactly as the CLI calls it.
    const source = demoPng();
    const expected = (await prep(source, toPrepOptions(options))).png;

    // 2. Browser: the same conversion, driven through the page's own UI.
    const params = new URLSearchParams();
    for (const [key, value] of Object.entries(options)) {
      const fallback = DEFAULT_OPTIONS[key as keyof PrepOptionsUi];
      if (value === fallback) continue;
      params.set(key, typeof value === "boolean" ? "1" : String(value));
    }
    await page.goto(`/#${params.toString()}`);
    await page.getByTestId("load-demo").click();
    await expect(page.getByTestId("export-png")).toBeVisible();

    const [download] = await Promise.all([
      page.waitForEvent("download"),
      page.getByTestId("export-png").click(),
    ]);
    const path = await download.path();
    expect(path).toBeTruthy();
    const actual = new Uint8Array(await readFile(path as string));

    // 3. The contract.
    expect(actual.length).toBe(expected.length);
    expect(sha256(actual)).toBe(sha256(expected));
  });
}

/**
 * A game the page builds itself must match the CLI's cartridge exactly.
 *
 * `caves` is the case worth pinning: a hand-drawn level, a scrolling camera,
 * object art *and* legend art. Everything the compiler and the image pipeline do
 * is in those kilobytes, so a single divergent byte anywhere shows up here.
 *
 * Once per console with a backend, because they share a compiler and share
 * nothing below it: the code is a different instruction set each time, the art
 * goes through a different fitter — mono shades, a fixed master palette, a
 * sixteen-colour bank — and the cartridge is wrapped differently. A page that
 * agreed with the CLI about the Game Boy would say nothing about whether it
 * agreed about the NES or the Master System.
 *
 * The fixtures are read off disk rather than imported from the page's bundle:
 * the page gets them through Vite's `?raw`, which only exists inside a build,
 * and the point of the test is that both sides start from the same file.
 */
for (const consoleId of ["gb", "nes", "sms"] as const) {
  test(`the ${consoleId} ROM the page builds is byte-identical to the CLI's`, async ({ page }) => {
    // Demaking a full-screen picture is seconds of real work and the runner is
    // shared, so the budget is the *slowest* thing this can legitimately take
    // rather than the fastest it has been seen to. What is being asserted is
    // byte-identity; how long the page took to get there is not the claim, and a
    // tight limit here only ever fails on someone else's busy machine.
    test.slow();
    const fixtures = dirname(
      createRequire(import.meta.url).resolve("@demake/demotic/fixtures/pong.dmt"),
    );
    const games = join(fixtures, "games");
    const program = compile(await readFile(join(games, "caves.dmt"), "utf8"), {
      profile: getProfile(consoleId),
      levels: { "cavern.dmtl": await readFile(join(games, "cavern.dmtl"), "utf8") },
    });
    // Every asset the program names, rather than a list: the page loads what the
    // game asks for, so a list here would only ever be a way to compare a ROM
    // built with art against one built without it. Music and effects are in that
    // set too — the cartridge the page hands you has its soundtrack demade into
    // it, and a Node build without one would differ by five kilobytes.
    const assets = new Map<string, Uint8Array>();
    for (const name of [...program.assets, ...program.tracks, ...program.sounds]) {
      assets.set(name, new Uint8Array(await readFile(join(games, name))));
    }
    const expected = (await buildGame(program, { title: "caves", assets })).bytes;

    await page.goto("/#section=game");
    await page.getByTestId("example-select").selectOption("caves");
    if (consoleId !== "gb") await page.getByTestId("console-select").selectOption(consoleId);
    // Waiting on the *cartridge's* console, not the picker's: demaking a
    // full-screen picture in colour is the whole `prep` tournament, and until it
    // finishes the pane is still playing — and still offering — the last one.
    await expect(page.getByTestId("rom-canvas")).toHaveAttribute("data-console", consoleId, {
      timeout: 150_000,
    });

    const [download] = await Promise.all([
      page.waitForEvent("download"),
      page.getByTestId("rom-download").click(),
    ]);
    const path = await download.path();
    expect(path).toBeTruthy();
    const actual = new Uint8Array(await readFile(path as string));

    expect(actual.length).toBe(expected.length);
    expect(sha256(actual)).toBe(sha256(expected));
  });
}

/** The bytes behind one of the page's download buttons. */
async function save(page: Page, testId: string): Promise<Uint8Array> {
  const [download] = await Promise.all([
    page.waitForEvent("download"),
    page.getByTestId(testId).click(),
  ]);
  const path = await download.path();
  expect(path).toBeTruthy();
  return new Uint8Array(await readFile(path as string));
}

/** Where the example library lives on disk. */
function fixtureDir(): string {
  return dirname(createRequire(import.meta.url).resolve("@demake/demotic/fixtures/pong.dmt"));
}

/**
 * The music demaker's four outputs, in the page and in Node.
 *
 * The WAV is the one doc 07 names, and it is the strictest: a difference of a
 * single least-significant bit anywhere in the chip model, the mixer, the DC
 * blocker or the box integration shows up as a different hash. The `.vgm`, the
 * sidecar and the cartridge come along because they are what the buttons offer,
 * and a page that produced a different *cartridge* from the CLI would break the
 * same promise in a place nobody would think to listen for.
 */
test("the music demaker's artifacts are byte-identical to Node's", async ({ page }) => {
  // 1. Node: the engine, called exactly as the CLI calls it. The subject is the
  //    first bundled track, which is what the section loads on its own.
  const source = new Uint8Array(await readFile(join(fixtureDir(), "rally.mid")));
  const result = arrangeScore(parseMidi(source), toArrangeOptions(DEFAULT_ARRANGE));
  const expected = {
    vgm: result.artifact,
    wav: encodeWav(render(result.script, toRenderOptions(DEFAULT_ARRANGE))),
    manifest: encodeAudioManifest(arrangeManifest(result)),
    rom: buildAudioRom(result.script, { title: "rally" }).bytes,
  };

  // 2. Browser: the same conversion, driven through the page's own buttons.
  await page.goto("/#section=music");
  await expect(page.getByTestId("channel-plan")).toBeVisible();

  for (const [what, bytes] of Object.entries(expected)) {
    const actual = await save(page, `export-${what}`);
    expect(actual.length, `${what} length`).toBe(bytes.length);
    expect(sha256(actual), `${what} bytes`).toBe(sha256(bytes));
  }
});

/**
 * And the sound demaker's, which exercises a different half of the engine.
 *
 * `sfx` reaches the chip models through the fitting loop rather than the
 * arranger — every candidate is *rendered* to be scored — so an engine-dependent
 * transcendental in the DSP would change which gesture won, not merely how the
 * winner sounds. That failure would be invisible in a waveform diff and obvious
 * here.
 */
test("the sound demaker's artifacts are byte-identical to Node's", async ({ page }) => {
  const source = new Uint8Array(await readFile(join(fixtureDir(), "bounce.wav")));
  const result = await demakeSfx(source, toSfxOptions(DEFAULT_SFX));
  const expected = {
    vgm: result.artifact,
    wav: encodeWav(render(result.script, toRenderOptions(DEFAULT_SFX))),
    manifest: encodeAudioManifest(sfxManifest(result)),
    rom: buildAudioRom(result.script, { title: "bounce" }).bytes,
  };

  await page.goto("/#section=sound");
  await expect(page.getByTestId("envelope")).toBeVisible();

  for (const [what, bytes] of Object.entries(expected)) {
    const actual = await save(page, `export-${what}`);
    expect(actual.length, `${what} length`).toBe(bytes.length);
    expect(sha256(actual), `${what} bytes`).toBe(sha256(bytes));
  }
});
