/**
 * Browser ⇄ Node determinism (doc 07 §Principles: "parity is a contract",
 * doc 10 §Determinism tests).
 *
 * The claim under test is exact: converting the same image with the same
 * options must produce **byte-identical** output in the browser and on the
 * command line — in every engine. So each case runs `prep` twice: once here in
 * Node through `@demake/core`, once in the page through its Web Worker, and the
 * two PNGs are compared byte-for-byte (via SHA-256 plus a length check).
 *
 * The page is driven through its real export path — the same download button a
 * user clicks — so nothing test-only stands in for the product.
 *
 * The subject is the bundled demo image, which is generated by shared code with
 * no transcendentals or randomness, so "the same input" is itself provable
 * rather than assumed.
 */

import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";

import { encodeRgbaPng, prep } from "@demake/core";
import { expect, test } from "@playwright/test";

import { buildDemoImage } from "../../src/lib/demo-image.ts";
import { toPrepOptions, DEFAULT_OPTIONS } from "../../src/lib/options.ts";
import type { PrepOptionsUi } from "../../src/worker/protocol.ts";

const sha256 = (bytes: Uint8Array): string =>
  createHash("sha256").update(Buffer.from(bytes)).digest("hex");

/** The exact bytes the app's "Load demo image" button feeds the engine. */
function demoPng(): Uint8Array {
  const { width, height, data } = buildDemoImage();
  return encodeRgbaPng(width, height, data);
}

/**
 * Cases chosen to exercise different pipeline corners: the mono path, a
 * fixed-master console with 16×16 attribute cells, a 15-bit RGB console with an
 * explicit dither, and a run with a non-default seed and effort.
 */
const CASES: { name: string; options: PrepOptionsUi }[] = [
  { name: "gbc-default", options: { ...DEFAULT_OPTIONS } },
  { name: "dmg-mono", options: { ...DEFAULT_OPTIONS, console: "dmg" } },
  { name: "nes-fixed-master", options: { ...DEFAULT_OPTIONS, console: "nes", effort: "fast" } },
  {
    name: "snes-dithered",
    options: { ...DEFAULT_OPTIONS, console: "snes", dither: "bayer4", seed: "1234" },
  },
];

for (const { name, options } of CASES) {
  test(`browser output is byte-identical to Node — ${name}`, async ({ page }) => {
    // 1. Node: the CLI's engine, called exactly as the CLI calls it.
    const source = demoPng();
    const expected = (await prep(source, toPrepOptions(options))).png;

    // 2. Browser: the same conversion, driven through the page's own UI.
    const params = new URLSearchParams();
    for (const [key, value] of Object.entries(options)) {
      const fallback = DEFAULT_OPTIONS[key as keyof PrepOptionsUi];
      if (value === fallback) continue;
      params.set(key, typeof value === "boolean" ? "1" : String(value));
    }
    await page.goto(`/#${params.toString()}`);
    await page.getByTestId("load-demo").click();
    await expect(page.getByTestId("export-png")).toBeVisible();

    const [download] = await Promise.all([
      page.waitForEvent("download"),
      page.getByTestId("export-png").click(),
    ]);
    const path = await download.path();
    expect(path).toBeTruthy();
    const actual = new Uint8Array(await readFile(path as string));

    // 3. The contract.
    expect(actual.length).toBe(expected.length);
    expect(sha256(actual)).toBe(sha256(expected));
  });
}
